server:
  port: 8081
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
greeting-service:
  greeting: "Pronto"
  defaultValue: "Mondo"
